#pragma once

#define MK_3_SPEED

#define AUTO_SHIFT_TIMEOUT 160
#define AUTO_SHIFT_DISABLED_AT_STARTUP
#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 3000
#define HOLD_ON_OTHER_KEY_PRESS
#define QUICK_TAP_TERM 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
